version: '3.8'

services:
  invoice-ocr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoice-ocr-system
    ports:
      - "8000:8000"
    volumes:
      - ./invoices:/app/invoices
      - ./data:/app/data
      - invoice_logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///./data/invoices.db
      - PYTHONPATH=/app
      - INVOICE_DIR=/app/invoices
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - invoice-network

  # 可选：添加数据库管理界面
  adminer:
    image: adminer
    container_name: invoice-db-admin
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=invoice-ocr
    networks:
      - invoice-network
    profiles:
      - admin

volumes:
  invoice_logs:
    driver: local

networks:
  invoice-network:
    driver: bridge
