name: Docker Test

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  test-docker-auth:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug Docker Hub credentials
      run: |
        echo "Testing Docker Hub authentication..."
        echo "Username length: ${#DOCKERHUB_USERNAME}"
        echo "Token length: ${#DOCKERHUB_TOKEN}"
        echo "Username starts with: ${DOCKERHUB_USERNAME:0:3}..."
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Test Docker Hub login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Test simple build
      run: |
        echo "FROM alpine:latest" > Dockerfile.test
        echo "RUN echo 'test'" >> Dockerfile.test
        docker build -f Dockerfile.test -t test-image .
        
    - name: Test push to Docker Hub
      run: |
        docker tag test-image ${{ secrets.DOCKERHUB_USERNAME }}/test:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/test:latest
